### ISSUE TITLE
using Redux

### ISSUE THREAD

**Issue by kaddopur** [Purple-Ninja/url-monster#8]
@maxis1718 

This app is fairly simple, but we could still try to introduce `redux` into this project.

Pros
- no internal states in `<App />`
- extract state-updating logic to `reducers`, instead of `<App />`
- ~~no passing callbacks to child *Components*. just import `actions`~~,
- easy to write test for state-updating logic

Cons
- tons of files (reducers, actions)

*reference*
- http://redux.js.org/
- https://github.com/erikras/ducks-modular-redux
[1]: http://redux.js.org/
[2]: https://github.com/erikras/ducks-modular-redux

**Comment by chienwenchen** [comment]
I think it is good to try Redux.
